name: dinckallapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dotted_dashed_line: ^0.0.3
  fl_chart: ^0.68.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  go_router: ^14.1.2
  google_nav_bar: ^5.0.6
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  simple_animation_progress_bar: ^1.8.2
  simple_circular_progress_bar: ^1.0.2
  sqflite: ^2.3.3+1
  syncfusion_flutter_charts: ^25.2.7
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/images/göğüs.jpeg
  - assets/images/Diz-Çekmekarın.png
  - assets/images/Bench_Pressgöğüs.png
  - assets/images/Cable_Flygöğüs.png
  - assets/images/DB_Flygöğüs.png
  - assets/images/DB_Pressgöğüs.png
  - assets/images/PushUpgöğüs.png
  - assets/images/Machine_Flygöğüs.png
  - assets/images/Bench_dipskol.png
  - assets/images/Biceps_Curlkol.png
  - assets/images/Cable_Pushdownkol.png
  - assets/images/Concentration_Curlkol.png
  - assets/images/Hammer_Curlkol.png
  - assets/images/Preacher_Curlkol.png
  - assets/images/DB_Squat-1,2bacak.png
  - assets/images/DB_Squat-1bacak.png
  - assets/images/Hip_Thrustbacak.png
  - assets/images/Hip Adductionbacak.png
  - assets/images/Leg Extensionbacak.png
  - assets/images/Leg_Curlbacak.png
  - assets/images/Lungesbacak.png
  - assets/images/Squatbacak.png

fonsts:
  - family: Poppins
    fonts:
      - asset: dinckalapp/assets/fonts/Poppins-Regular.ttf
      - asset: dinckalapp/assets/fonts/Poppins-Bold.ttf
        weight: 700
